$(document).ready(function(){
	$("#vocch").click(function(){
		$("#ch1").toggle();
		$("#ch2").toggle();
	});
	$("#ch1").click(function(){
			$("#voc1").toggle();
	});
	$("#ch2").click(function(){
			$("#voc2").toggle();
	});
	$("#def1").hide();
	$("#def2").hide();
	$("#def3").hide();
	$("#def4").hide();
	$("#def5").hide();
	$("#def6").hide();
	$("#def7").hide();
	$("#def8").hide();
	$("#def9").hide();
	$("#def10").hide();
	$("#def11").hide();
	$("#def12").hide();
	$("#def13").hide();
	$("#def14").hide();
	$("#def15").hide();
	$("#def16").hide();
	$("#def17").hide();
	$("#def18").hide();
	$("#def19").hide();
	$("#def20").hide();
	$("#def21").hide();
	$("#def22").hide();
	$("#vocab1").click(function(){
		$("#def1").toggle();
	});
	$("#vocab2").click(function(){
		$("#def2").toggle();
	});
	$("#vocab3").click(function(){
		$("#def3").toggle();
	});
	$("#vocab4").click(function(){
		$("#def4").toggle();
	});
	$("#vocab5").click(function(){
		$("#def5").toggle();
	});
	$("#vocab6").click(function(){
		$("#def6").toggle();
	});
	$("#vocab7").click(function(){
		$("#def7").toggle();
	});
	$("#vocab8").click(function(){
		$("#def8").toggle();
	});
	$("#vocab9").click(function(){
		$("#def9").toggle();
	});
	$("#vocab10").click(function(){
		$("#def10").toggle();
	});
	$("#vocab11").click(function(){
		$("#def11").toggle();
	});
	$("#vocab12").click(function(){
		$("#def12").toggle();
	});
	$("#vocab13").click(function(){
		$("#def13").toggle();
	});
	$("#vocab14").click(function(){
		$("#def14").toggle();
	});
	$("#vocab15").click(function(){
		$("#def15").toggle();
	});
	$("#vocab16").click(function(){
		$("#def16").toggle();
	});
	$("#vocab17").click(function(){
		$("#def17").toggle();
	});
	$("#vocab18").click(function(){
		$("#def18").toggle();
	});
	$("#vocab19").click(function(){
		$("#def19").toggle();
	});
	$("#vocab20").click(function(){
		$("#def20").toggle();
	});
	$("#vocab21").click(function(){
		$("#def21").toggle();
	});
	$("#vocab22").click(function(){
		$("#def22").toggle();
	});
	//$("#one").click(function(){
		//$(".hide").toggle();
		//$("img").show();
	//});
});