$(document).ready(function(){
	$("#def1").hide();
	$("#def2").hide();
	$("#def3").hide();
	$("#def4").hide();
	$("#def5").hide();
	$("#def6").hide();
	$("#def7").hide();
	$("#def8").hide();
	$("#def9").hide();
	$("#def10").hide();
	$("#def11").hide();
	$("#vocab1").click(function(){
		$("#def1").toggle();
	});
	$("#vocab2").click(function(){
		$("#def2").toggle();
	});
	$("#vocab3").click(function(){
		$("#def3").toggle();
	});
	$("#vocab4").click(function(){
		$("#def4").toggle();
	});
	$("#vocab5").click(function(){
		$("#def5").toggle();
	});
	$("#vocab6").click(function(){
		$("#def6").toggle();
	});
	$("#vocab7").click(function(){
		$("#def7").toggle();
	});
	$("#vocab8").click(function(){
		$("#def8").toggle();
	});
	$("#vocab9").click(function(){
		$("#def9").toggle();
	});
	$("#vocab10").click(function(){
		$("#def10").toggle();
	});
	$("#vocab11").click(function(){
		$("#def11").toggle();
	});
	//$("#one").click(function(){
		//$(".hide").toggle();
		//$("img").show();
	//});
});